version: '3.6'

services:

  partido:
    build:
      context: ./services/partido
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@partido-db:5432/partido_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@partido-db:5432/partido_test
    depends_on: 
      - partido-db

  partido-db:
    build:
      context: ./services/partido/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - partido